# SPDX-License-Identifier: GPL-2.0
#
# Spacemit Clock specific Makefile
#

#SoC support
obj-$(CONFIG_SPACEMIT_K1X_CCU)     += ccu-spacemit-k1x.o ccu_mix.o ccu_pll.o ccu_dpll.o ccu_ddn.o ccu_ddr.o
obj-$(CONFIG_SPACEMIT_K1PRO_CCU)   += ccu-spacemit-k1pro.o
