# SPDX-License-Identifier: GPL-2.0

dtbo-$(CONFIG_BOARD_BANANAPI_M4BERRY) += \
	bpi-m4berry-i2c3.dtbo \
	bpi-m4berry-i2c4.dtbo \
	bpi-m4berry-uart1.dtbo \
	bpi-m4berry-pg-uart2.dtbo \
	bpi-m4berry-ph-uart2.dtbo \
	bpi-m4berry-uart5.dtbo \
	bpi-m4berry-pwm1.dtbo \
	bpi-m4berry-pwm1-beeper.dtbo \
	bpi-m4berry-pwm1-fan.dtbo \
	bpi-m4berry-spi1.dtbo \
	bpi-m4berry-spi1-flash.dtbo \
	bpi-m4berry-waveshare-tft24.dtbo \
	bpi-m4berry-waveshare-tft35c.dtbo \
	bpi-m4berry-spdifout.dtbo \
	bpi-m4berry-i2smic-mems.dtbo \
	bpi-m4berry-nxez-pcm512x-hifi.dtbo \
	bpi-m4berry-waveshare-wm8960-hifi.dtbo \
	bpi-m4berry-ds3231.dtbo

targets += $(dtbo-y)

always := $(dtbo-y)
clean-files := *.dtbo
