// SPDX-License-Identifier: GPL-2.0
/* Copyright (C) 2019 Synaptics Incorporated */
#ifndef ___HDMIRX_H__
#define ___HDMIRX_H__

#define HRX_MSG_DESTROY_ISR_TASK                1

/* id_main_unit_interrupt Registers */
#define HDMI_MAINUNIT_0_INT_STATUS      0x5010
#define HDMI_MAINUNIT_0_INT_MASK_N      0x5014
#define HDMI_MAINUNIT_0_INT_CLEAR       0x5018
#define HDMI_MAINUNIT_0_INT_FORCE       0x501C
#define HDMI_MAINUNIT_1_INT_STATUS      0x5020
#define HDMI_MAINUNIT_1_INT_MASK_N      0x5024
#define HDMI_MAINUNIT_1_INT_CLEAR       0x5028
#define HDMI_MAINUNIT_1_INT_FORCE       0x502C
#define HDMI_MAINUNIT_2_INT_STATUS      0x5030
#define HDMI_MAINUNIT_2_INT_MASK_N      0x5034
#define HDMI_MAINUNIT_2_INT_CLEAR       0x5038
#define HDMI_MAINUNIT_2_INT_FORCE       0x503C

/* id_avpunit_interrupt Registers */
#define HDMI_AVPUNIT_0_INT_STATUS       0x5040
#define HDMI_AVPUNIT_0_INT_MASK_N       0x5044
#define HDMI_AVPUNIT_0_INT_CLEAR        0x5048
#define HDMI_AVPUNIT_0_INT_FORCE        0x504C
#define HDMI_AVPUNIT_1_INT_STATUS       0x5050
#define HDMI_AVPUNIT_1_INT_MASK_N       0x5054
#define HDMI_AVPUNIT_1_INT_CLEAR        0x5058
#define HDMI_AVPUNIT_1_INT_FORCE        0x505C

/* id_packet_interrupt Registers */
#define HDMI_PKT_0_INT_STATUS           0x5080
#define HDMI_PKT_0_INT_MASK_N           0x5084
#define HDMI_PKT_0_INT_CLEAR            0x5088
#define HDMI_PKT_0_INT_FORCE            0x508C
#define HDMI_PKT_1_INT_STATUS           0x5090
#define HDMI_PKT_1_INT_MASK_N           0x5094
#define HDMI_PKT_1_INT_CLEAR            0x5098
#define HDMI_PKT_1_INT_FORCE            0x509C

/* id_scdc_interrupt Registers */
#define HDMI_SCDC_INT_STATUS            0x50C0
#define HDMI_SCDC_INT_MASK_N            0x50C4
#define HDMI_SCDC_INT_CLEAR             0x50C8
#define HDMI_SCDC_INT_FORCE             0x50CC

/* id_hdcp_interrupt Registers */
#define HDMI_HDCP_INT_STATUS            0x50D0
#define HDMI_HDCP_INT_MASK_N            0x50D4
#define HDMI_HDCP_INT_CLEAR             0x50D8
#define HDMI_HDCP_INT_FORCE             0x50DC

/* id_cec_interrupt Registers */
#define HDMI_CEC_INT_STATUS             0x5100
#define HDMI_CEC_INT_MASK_N             0x5104
#define HDMI_CEC_INT_CLEAR              0x5108
#define HDMI_CEC_INT_FORCE              0x510C

enum {
/* --- id_main_unit_interrupt --- */
	/* MAINUNIT_0_INT_STATUS field values */
	HDMI_MAINUNIT_0_INT_STATUS_REGBANK_READY = BIT(31),
	HDMI_MAINUNIT_0_INT_STATUS_APB_IF_READY = BIT(30),
	HDMI_MAINUNIT_0_INT_STATUS_TIMER_BASE_LOCKED = BIT(26),
	HDMI_MAINUNIT_0_INT_STATUS_TMDSQP_CK_OFF = BIT(5),
	HDMI_MAINUNIT_0_INT_STATUS_TMDSQP_CK_LOCKED = BIT(4),
	HDMI_MAINUNIT_0_INT_STATUS_AUDIO_CK_OFF = BIT(1),
	HDMI_MAINUNIT_0_INT_STATUS_AUDIO_CK_LOCKED = BIT(0),
	/* MAINUNIT_0_INT_MASK_N field values */
	HDMI_MAINUNIT_0_INT_MASK_N_REGBANK_READY_MASK = BIT(31),
	HDMI_MAINUNIT_0_INT_MASK_N_REGBANK_READY_OFFSET = 31,
	HDMI_MAINUNIT_0_INT_MASK_N_APB_IF_READY_MASK = BIT(30),
	HDMI_MAINUNIT_0_INT_MASK_N_APB_IF_READY_OFFSET = 30,
	HDMI_MAINUNIT_0_INT_MASK_N_TIMER_BASE_LOCKED_MASK = BIT(26),
	HDMI_MAINUNIT_0_INT_MASK_N_TIMER_BASE_LOCKED_OFFSET = 26,
	HDMI_MAINUNIT_0_INT_MASK_N_TMDSQP_CK_OFF_MASK = BIT(5),
	HDMI_MAINUNIT_0_INT_MASK_N_TMDSQP_CK_OFF_OFFSET = 5,
	HDMI_MAINUNIT_0_INT_MASK_N_TMDSQP_CK_LOCKED_MASK = BIT(4),
	HDMI_MAINUNIT_0_INT_MASK_N_TMDSQP_CK_LOCKED_OFFSET = 4,
	HDMI_MAINUNIT_0_INT_MASK_N_AUDIO_CK_OFF_MASK = BIT(1),
	HDMI_MAINUNIT_0_INT_MASK_N_AUDIO_CK_OFF_OFFSET = 1,
	HDMI_MAINUNIT_0_INT_MASK_N_AUDIO_CK_LOCKED_MASK = BIT(0),
	HDMI_MAINUNIT_0_INT_MASK_N_AUDIO_CK_LOCKED_OFFSET = 0,
	/* MAINUNIT_0_INT_CLEAR field values */
	HDMI_MAINUNIT_0_INT_CLEAR_REGBANK_READY_MASK = BIT(31),
	HDMI_MAINUNIT_0_INT_CLEAR_REGBANK_READY_OFFSET = 31,
	HDMI_MAINUNIT_0_INT_CLEAR_APB_IF_READY_MASK = BIT(30),
	HDMI_MAINUNIT_0_INT_CLEAR_APB_IF_READY_OFFSET = 30,
	HDMI_MAINUNIT_0_INT_CLEAR_TIMER_BASE_LOCKED_MASK = BIT(26),
	HDMI_MAINUNIT_0_INT_CLEAR_TIMER_BASE_LOCKED_OFFSET = 26,
	HDMI_MAINUNIT_0_INT_CLEAR_TMDSQP_CK_OFF_MASK = BIT(5),
	HDMI_MAINUNIT_0_INT_CLEAR_TMDSQP_CK_OFF_OFFSET = 5,
	HDMI_MAINUNIT_0_INT_CLEAR_TMDSQP_CK_LOCKED_MASK = BIT(4),
	HDMI_MAINUNIT_0_INT_CLEAR_TMDSQP_CK_LOCKED_OFFSET = 4,
	HDMI_MAINUNIT_0_INT_CLEAR_AUDIO_CK_OFF_MASK = BIT(1),
	HDMI_MAINUNIT_0_INT_CLEAR_AUDIO_CK_OFF_OFFSET = 1,
	HDMI_MAINUNIT_0_INT_CLEAR_AUDIO_CK_LOCKED_MASK = BIT(0),
	HDMI_MAINUNIT_0_INT_CLEAR_AUDIO_CK_LOCKED_OFFSET = 0,
	/* MAINUNIT_1_INT_STATUS field values */
	HDMI_MAINUNIT_1_INT_STATUS_CEC_POWERED_DOWN = BIT(13),
	HDMI_MAINUNIT_1_INT_STATUS_CEC_POWERED_UP = BIT(12),
	HDMI_MAINUNIT_1_INT_STATUS_AVPUNIT_POWERED_DOWN = BIT(1),
	HDMI_MAINUNIT_1_INT_STATUS_AVPUNIT_POWERED_UP = BIT(0),
	/* MAINUNIT_1_INT_MASK_N field values */
	HDMI_MAINUNIT_1_INT_MASK_N_CEC_POWERED_DOWN_MASK = BIT(13),
	HDMI_MAINUNIT_1_INT_MASK_N_CEC_POWERED_DOWN_OFFSET = 13,
	HDMI_MAINUNIT_1_INT_MASK_N_CEC_POWERED_UP_MASK = BIT(12),
	HDMI_MAINUNIT_1_INT_MASK_N_CEC_POWERED_UP_OFFSET = 12,
	HDMI_MAINUNIT_1_INT_MASK_N_AVPUNIT_POWERED_DOWN_MASK = BIT(1),
	HDMI_MAINUNIT_1_INT_MASK_N_AVPUNIT_POWERED_DOWN_OFFSET = 1,
	HDMI_MAINUNIT_1_INT_MASK_N_AVPUNIT_POWERED_UP_MASK = BIT(0),
	HDMI_MAINUNIT_1_INT_MASK_N_AVPUNIT_POWERED_UP_OFFSET = 0,
	/* MAINUNIT_1_INT_CLEAR field values */
	HDMI_MAINUNIT_1_INT_CLEAR_CEC_POWERED_DOWN_MASK = BIT(13),
	HDMI_MAINUNIT_1_INT_CLEAR_CEC_POWERED_DOWN_OFFSET = 13,
	HDMI_MAINUNIT_1_INT_CLEAR_CEC_POWERED_UP_MASK = BIT(12),
	HDMI_MAINUNIT_1_INT_CLEAR_CEC_POWERED_UP_OFFSET = 12,
	HDMI_MAINUNIT_1_INT_CLEAR_AVPUNIT_POWERED_DOWN_MASK = BIT(1),
	HDMI_MAINUNIT_1_INT_CLEAR_AVPUNIT_POWERED_DOWN_OFFSET = 1,
	HDMI_MAINUNIT_1_INT_CLEAR_AVPUNIT_POWERED_UP_MASK = BIT(0),
	HDMI_MAINUNIT_1_INT_CLEAR_AVPUNIT_POWERED_UP_OFFSET = 0,
	/* MAINUNIT_2_INT_STATUS field values */
	HDMI_MAINUNIT_2_STATUS_PHYCREG_CR_TIMEOUT_MASK = BIT(12),
	HDMI_MAINUNIT_2_STATUS_PHYCREG_CR_TIMEOUT_OFFSET = 12,
	HDMI_MAINUNIT_2_STATUS_PHYCREG_CR_READ_DONE_MASK = BIT(11),
	HDMI_MAINUNIT_2_STATUS_PHYCREG_CR_READ_DONE_OFFSET = 11,
	HDMI_MAINUNIT_2_STATUS_PHYCREG_CR_WRITE_DONE_MASK = BIT(10),
	HDMI_MAINUNIT_2_STATUS_PHYCREG_CR_WRITE_DONE_OFFSET = 10,
	HDMI_MAINUNIT_2_STATUS_PHYCREG_CR_SELECTIONMODE_DONE_MASK = BIT(8),
	HDMI_MAINUNIT_2_STATUS_PHYCREG_CR_SELECTIONMODE_DONE_OFFSET = 8,
	HDMI_MAINUNIT_2_INT_STATUS_TMDSVALID_STABLE = BIT(1),
	HDMI_MAINUNIT_2_INT_STATUS_AUDPLL_LOCK_STABLE = BIT(0),
	/* MAINUNIT_2_INT_MASK_N field values */
	HDMI_MAINUNIT_2_INT_MASK_N_PHYCREG_CR_TIMEOUT_MASK = BIT(12),
	HDMI_MAINUNIT_2_INT_MASK_N_PHYCREG_CR_TIMEOUT_OFFSET = 12,
	HDMI_MAINUNIT_2_INT_MASK_N_PHYCREG_CR_READ_DONE_MASK = BIT(11),
	HDMI_MAINUNIT_2_INT_MASK_N_PHYCREG_CR_READ_DONE_OFFSET = 11,
	HDMI_MAINUNIT_2_INT_MASK_N_PHYCREG_CR_WRITE_DONE_MASK = BIT(10),
	HDMI_MAINUNIT_2_INT_MASK_N_PHYCREG_CR_WRITE_DONE_OFFSET = 10,
	HDMI_MAINUNIT_2_INT_MASK_N_PHYCREG_CR_SELECTIONMODE_DONE_MASK = BIT(8),
	HDMI_MAINUNIT_2_INT_MASK_N_PHYCREG_CR_SELECTIONMODE_DONE_OFFSET = 8,
	HDMI_MAINUNIT_2_INT_MASK_N_TMDSVALID_STABLE_MASK = BIT(1),
	HDMI_MAINUNIT_2_INT_MASK_N_TMDSVALID_STABLE_OFFSET = 1,
	HDMI_MAINUNIT_2_INT_MASK_N_AUDPLL_LOCK_STABLE_MASK = BIT(0),
	HDMI_MAINUNIT_2_INT_MASK_N_AUDPLL_LOCK_STABLE_OFFSET = 0,
	/* MAINUNIT_2_INT_CLEAR field values */
	HDMI_MAINUNIT_2_CLEAR_PHYCREG_CR_TIMEOUT_MASK = BIT(12),
	HDMI_MAINUNIT_2_CLEAR_PHYCREG_CR_TIMEOUT_OFFSET = 12,
	HDMI_MAINUNIT_2_CLEAR_PHYCREG_CR_READ_DONE_MASK = BIT(11),
	HDMI_MAINUNIT_2_CLEAR_PHYCREG_CR_READ_DONE_OFFSET = 11,
	HDMI_MAINUNIT_2_CLEAR_PHYCREG_CR_WRITE_DONE_MASK = BIT(10),
	HDMI_MAINUNIT_2_CLEAR_PHYCREG_CR_WRITE_DONE_OFFSET = 10,
	HDMI_MAINUNIT_2_CLEAR_PHYCREG_CR_SELECTIONMODE_DONE_MASK = BIT(8),
	HDMI_MAINUNIT_2_CLEAR_PHYCREG_CR_SELECTIONMODE_DONE_OFFSET = 8,
	HDMI_MAINUNIT_2_INT_CLEAR_TMDSVALID_STABLE_MASK = BIT(1),
	HDMI_MAINUNIT_2_INT_CLEAR_TMDSVALID_STABLE_OFFSET = 1,
	HDMI_MAINUNIT_2_INT_CLEAR_AUDPLL_LOCK_STABLE_MASK = BIT(0),
	HDMI_MAINUNIT_2_INT_CLEAR_AUDPLL_LOCK_STABLE_OFFSET = 0,
/* --- id_avpunit_interrupt --- */
	/* AVPUNIT_1_INT_STATUS field values */
	HDMI_AVPUNIT_1_INT_STATUS_VMON_VMEAS = BIT(31),
	HDMI_AVPUNIT_1_INT_STATUS_VMON_HMEAS = BIT(30),
	HDMI_AVPUNIT_1_INT_STATUS_AUD_CHSTATUS_SP3 = BIT(24),
	HDMI_AVPUNIT_1_INT_STATUS_AUD_CHSTATUS_SP2 = BIT(23),
	HDMI_AVPUNIT_1_INT_STATUS_AUD_CHSTATUS_SP1 = BIT(22),
	HDMI_AVPUNIT_1_INT_STATUS_AUD_CHSTATUS_SP0 = BIT(21),
	HDMI_AVPUNIT_1_INT_STATUS_AUD_MUTE = BIT(20),
	HDMI_AVPUNIT_1_INT_STATUS_AFIFO_UNDERFLOW = BIT(19),
	HDMI_AVPUNIT_1_INT_STATUS_AFIFO_OVERFLOW = BIT(18),
	HDMI_AVPUNIT_1_INT_STATUS_AFIFO_THR_PASS = BIT(13),
	HDMI_AVPUNIT_1_INT_STATUS_DEFRAMER_DVIHDMI_CHG = BIT(3),
	HDMI_AVPUNIT_1_INT_STATUS_DEFRAMER_GBDET_ERR = BIT(2),
	/* AVPUNIT_1_INT_MASK_N field values */
	HDMI_AVPUNIT_1_INT_MASK_N_VMON_VMEAS_MASK = BIT(31),
	HDMI_AVPUNIT_1_INT_MASK_N_VMON_VMEAS_OFFSET = 31,
	HDMI_AVPUNIT_1_INT_MASK_N_VMON_HMEAS_MASK = BIT(30),
	HDMI_AVPUNIT_1_INT_MASK_N_VMON_HMEAS_OFFSET = 30,
	HDMI_AVPUNIT_1_INT_MASK_N_AUD_CHSTATUS_SP3_MASK = BIT(24),
	HDMI_AVPUNIT_1_INT_MASK_N_AUD_CHSTATUS_SP3_OFFSET = 24,
	HDMI_AVPUNIT_1_INT_MASK_N_AUD_CHSTATUS_SP2_MASK = BIT(23),
	HDMI_AVPUNIT_1_INT_MASK_N_AUD_CHSTATUS_SP2_OFFSET = 23,
	HDMI_AVPUNIT_1_INT_MASK_N_AUD_CHSTATUS_SP1_MASK = BIT(22),
	HDMI_AVPUNIT_1_INT_MASK_N_AUD_CHSTATUS_SP1_OFFSET = 22,
	HDMI_AVPUNIT_1_INT_MASK_N_AUD_CHSTATUS_SP0_MASK = BIT(21),
	HDMI_AVPUNIT_1_INT_MASK_N_AUD_CHSTATUS_SP0_OFFSET = 21,
	HDMI_AVPUNIT_1_INT_MASK_N_AUD_MUTE_MASK = BIT(20),
	HDMI_AVPUNIT_1_INT_MASK_N_AUD_MUTE_OFFSET = 20,
	HDMI_AVPUNIT_1_INT_MASK_N_AFIFO_UNDERFLOW_MASK = BIT(19),
	HDMI_AVPUNIT_1_INT_MASK_N_AFIFO_UNDERFLOW_OFFSET = 19,
	HDMI_AVPUNIT_1_INT_MASK_N_AFIFO_THR_PASS_MASK = BIT(13),
	HDMI_AVPUNIT_1_INT_MASK_N_AFIFO_THR_PASS_OFFSET = 13,
	HDMI_AVPUNIT_1_INT_MASK_N_AUD_FMT_CHG_MASK = BIT(12),
	HDMI_AVPUNIT_1_INT_MASK_N_AUD_FMT_CHG_OFFSET = 12,
	HDMI_AVPUNIT_1_INT_MASK_N_AFIFO_OVERFLOW_MASK = BIT(18),
	HDMI_AVPUNIT_1_INT_MASK_N_AFIFO_OVERFLOW_OFFSET = 18,
	HDMI_AVPUNIT_1_INT_MASK_N_DEFRAMER_DVIHDMI_CHG_MASK = BIT(3),
	HDMI_AVPUNIT_1_INT_MASK_N_DEFRAMER_DVIHDMI_CHG_OFFSET = 3,
	HDMI_AVPUNIT_1_INT_MASK_N_DEFRAMER_GBDET_ERR_MASK = BIT(2),
	HDMI_AVPUNIT_1_INT_MASK_N_DEFRAMER_GBDET_ERR_OFFSET = 2,
	HDMI_AVPUNIT_1_INT_MASK_N_DEFRAMER_VSYNC_MASK = BIT(0),
	HDMI_AVPUNIT_1_INT_MASK_N_DEFRAMER_VSYNC_OFFSET = 0,
	/* AVPUNIT_1_INT_CLEAR field values */
	HDMI_AVPUNIT_1_INT_CLEAR_VMON_VMEAS_MASK = BIT(31),
	HDMI_AVPUNIT_1_INT_CLEAR_VMON_VMEAS_OFFSET = 31,
	HDMI_AVPUNIT_1_INT_CLEAR_VMON_HMEAS_MASK = BIT(30),
	HDMI_AVPUNIT_1_INT_CLEAR_VMON_HMEAS_OFFSET = 30,
	HDMI_AVPUNIT_1_INT_CLEAR_AUD_CHSTATUS_SP3_MASK = BIT(24),
	HDMI_AVPUNIT_1_INT_CLEAR_AUD_CHSTATUS_SP3_OFFSET = 24,
	HDMI_AVPUNIT_1_INT_CLEAR_AUD_CHSTATUS_SP2_MASK = BIT(23),
	HDMI_AVPUNIT_1_INT_CLEAR_AUD_CHSTATUS_SP2_OFFSET = 23,
	HDMI_AVPUNIT_1_INT_CLEAR_AUD_CHSTATUS_SP1_MASK = BIT(22),
	HDMI_AVPUNIT_1_INT_CLEAR_AUD_CHSTATUS_SP1_OFFSET = 22,
	HDMI_AVPUNIT_1_INT_CLEAR_AUD_CHSTATUS_SP0_MASK = BIT(21),
	HDMI_AVPUNIT_1_INT_CLEAR_AUD_CHSTATUS_SP0_OFFSET = 21,
	HDMI_AVPUNIT_1_INT_CLEAR_AUD_MUTE_MASK = BIT(20),
	HDMI_AVPUNIT_1_INT_CLEAR_AUD_MUTE_OFFSET = 20,
	HDMI_AVPUNIT_1_INT_CLEAR_AFIFO_UNDERFLOW_MASK = BIT(19),
	HDMI_AVPUNIT_1_INT_CLEAR_AFIFO_UNDERFLOW_OFFSET = 19,
	HDMI_AVPUNIT_1_INT_CLEAR_AFIFO_OVERFLOW_MASK = BIT(18),
	HDMI_AVPUNIT_1_INT_CLEAR_AFIFO_OVERFLOW_OFFSET = 18,
	HDMI_AVPUNIT_1_INT_CLEAR_DEFRAMER_DVIHDMI_CHG_MASK = BIT(3),
	HDMI_AVPUNIT_1_INT_CLEAR_DEFRAMER_DVIHDMI_CHG_OFFSET = 3,
	HDMI_AVPUNIT_1_INT_CLEAR_DEFRAMER_GBDET_ERR_MASK = BIT(2),
	HDMI_AVPUNIT_1_INT_CLEAR_DEFRAMER_GBDET_ERR_OFFSET = 2,
/* --- id_packet_interrupt --- */
	/* PKT_0_INT_STATUS field values */
	HDMI_PKT_0_INT_STATUS_GENPKT1 = BIT(18),
	HDMI_PKT_0_INT_STATUS_GENPKT0 = BIT(17),
	HDMI_PKT_0_INT_STATUS_DRMIF = BIT(16),
	HDMI_PKT_0_INT_STATUS_NTSCVBIIF = BIT(15),
	HDMI_PKT_0_INT_STATUS_AUDIF = BIT(13),
	HDMI_PKT_0_INT_STATUS_SRCPDIF = BIT(12),
	HDMI_PKT_0_INT_STATUS_AVIIF = BIT(11),
	HDMI_PKT_0_INT_STATUS_VSIF = BIT(10),
	HDMI_PKT_0_INT_STATUS_AMD = BIT(9),
	HDMI_PKT_0_INT_STATUS_GMD = BIT(8),
	HDMI_PKT_0_INT_STATUS_ISRC2 = BIT(7),
	HDMI_PKT_0_INT_STATUS_ISRC1 = BIT(6),
	HDMI_PKT_0_INT_STATUS_ACP = BIT(5),
	HDMI_PKT_0_INT_STATUS_GCP = BIT(4),
	HDMI_PKT_0_INT_STATUS_ACR = BIT(3),
	HDMI_PKT_0_INT_STATUS_ACP_TIMEOUT = BIT(2),
	HDMI_PKT_0_INT_STATUS_ACR_N = BIT(1),
	HDMI_PKT_0_INT_STATUS_ACR_CTS = BIT(0),
	/* PKT_0_INT_MASK_N field values */
	HDMI_PKT_0_INT_MASK_N_GENPKT1_MASK = BIT(18),
	HDMI_PKT_0_INT_MASK_N_GENPKT1_OFFSET = 18,
	HDMI_PKT_0_INT_MASK_N_GENPKT0_MASK = BIT(17),
	HDMI_PKT_0_INT_MASK_N_GENPKT0_OFFSET = 17,
	HDMI_PKT_0_INT_MASK_N_DRMIF_MASK = BIT(16),
	HDMI_PKT_0_INT_MASK_N_DRMIF_OFFSET = 16,
	HDMI_PKT_0_INT_MASK_N_NTSCVBIIF_MASK = BIT(15),
	HDMI_PKT_0_INT_MASK_N_NTSCVBIIF_OFFSET = 15,
	HDMI_PKT_0_INT_MASK_N_AUDIF_MASK = BIT(13),
	HDMI_PKT_0_INT_MASK_N_AUDIF_OFFSET = 13,
	HDMI_PKT_0_INT_MASK_N_SRCPDIF_MASK = BIT(12),
	HDMI_PKT_0_INT_MASK_N_SRCPDIF_OFFSET = 12,
	HDMI_PKT_0_INT_MASK_N_AVIIF_MASK = BIT(11),
	HDMI_PKT_0_INT_MASK_N_AVIIF_OFFSET = 11,
	HDMI_PKT_0_INT_MASK_N_VSIF_MASK = BIT(10),
	HDMI_PKT_0_INT_MASK_N_VSIF_OFFSET = 10,
	HDMI_PKT_0_INT_MASK_N_AMD_MASK = BIT(9),
	HDMI_PKT_0_INT_MASK_N_AMD_OFFSET = 9,
	HDMI_PKT_0_INT_MASK_N_GMD_MASK = BIT(8),
	HDMI_PKT_0_INT_MASK_N_GMD_OFFSET = 8,
	HDMI_PKT_0_INT_MASK_N_ISRC2_MASK = BIT(7),
	HDMI_PKT_0_INT_MASK_N_ISRC2_OFFSET = 7,
	HDMI_PKT_0_INT_MASK_N_ISRC1_MASK = BIT(6),
	HDMI_PKT_0_INT_MASK_N_ISRC1_OFFSET = 6,
	HDMI_PKT_0_INT_MASK_N_ACP_MASK = BIT(5),
	HDMI_PKT_0_INT_MASK_N_ACP_OFFSET = 5,
	HDMI_PKT_0_INT_MASK_N_GCP_MASK = BIT(4),
	HDMI_PKT_0_INT_MASK_N_GCP_OFFSET = 4,
	HDMI_PKT_0_INT_MASK_N_ACR_MASK = BIT(3),
	HDMI_PKT_0_INT_MASK_N_ACR_OFFSET = 3,
	HDMI_PKT_0_INT_MASK_N_ACP_TIMEOUT_MASK = BIT(2),
	HDMI_PKT_0_INT_MASK_N_ACP_TIMEOUT_OFFSET = 2,
	HDMI_PKT_0_INT_MASK_N_ACR_N_MASK = BIT(1),
	HDMI_PKT_0_INT_MASK_N_ACR_N_OFFSET = 1,
	HDMI_PKT_0_INT_MASK_N_ACR_CTS_MASK = BIT(0),
	HDMI_PKT_0_INT_MASK_N_ACR_CTS_OFFSET = 0,
	/* PKT_0_INT_CLEAR field values */
	HDMI_PKT_0_INT_CLEAR_GENPKT1_MASK = BIT(18),
	HDMI_PKT_0_INT_CLEAR_GENPKT1_OFFSET = 18,
	HDMI_PKT_0_INT_CLEAR_GENPKT0_MASK = BIT(17),
	HDMI_PKT_0_INT_CLEAR_GENPKT0_OFFSET = 17,
	HDMI_PKT_0_INT_CLEAR_DRMIF_MASK = BIT(16),
	HDMI_PKT_0_INT_CLEAR_DRMIF_OFFSET = 16,
	HDMI_PKT_0_INT_CLEAR_NTSCVBIIF_MASK = BIT(15),
	HDMI_PKT_0_INT_CLEAR_NTSCVBIIF_OFFSET = 15,
	HDMI_PKT_0_INT_CLEAR_AUDIF_MASK = BIT(13),
	HDMI_PKT_0_INT_CLEAR_AUDIF_OFFSET = 13,
	HDMI_PKT_0_INT_CLEAR_SRCPDIF_MASK = BIT(12),
	HDMI_PKT_0_INT_CLEAR_SRCPDIF_OFFSET = 12,
	HDMI_PKT_0_INT_CLEAR_AVIIF_MASK = BIT(11),
	HDMI_PKT_0_INT_CLEAR_AVIIF_OFFSET = 11,
	HDMI_PKT_0_INT_CLEAR_VSIF_MASK = BIT(10),
	HDMI_PKT_0_INT_CLEAR_VSIF_OFFSET = 10,
	HDMI_PKT_0_INT_CLEAR_AMD_MASK = BIT(9),
	HDMI_PKT_0_INT_CLEAR_AMD_OFFSET = 9,
	HDMI_PKT_0_INT_CLEAR_GMD_MASK = BIT(8),
	HDMI_PKT_0_INT_CLEAR_GMD_OFFSET = 8,
	HDMI_PKT_0_INT_CLEAR_ISRC2_MASK = BIT(7),
	HDMI_PKT_0_INT_CLEAR_ISRC2_OFFSET = 7,
	HDMI_PKT_0_INT_CLEAR_ISRC1_MASK = BIT(6),
	HDMI_PKT_0_INT_CLEAR_ISRC1_OFFSET = 6,
	HDMI_PKT_0_INT_CLEAR_ACP_MASK = BIT(5),
	HDMI_PKT_0_INT_CLEAR_ACP_OFFSET = 5,
	HDMI_PKT_0_INT_CLEAR_GCP_MASK = BIT(4),
	HDMI_PKT_0_INT_CLEAR_GCP_OFFSET = 4,
	HDMI_PKT_0_INT_CLEAR_ACR_MASK = BIT(3),
	HDMI_PKT_0_INT_CLEAR_ACR_OFFSET = 3,
	HDMI_PKT_0_INT_CLEAR_ACP_TIMEOUT_MASK = BIT(2),
	HDMI_PKT_0_INT_CLEAR_ACP_TIMEOUT_OFFSET = 2,
	HDMI_PKT_0_INT_CLEAR_ACR_N_MASK = BIT(1),
	HDMI_PKT_0_INT_CLEAR_ACR_N_OFFSET = 1,
	HDMI_PKT_0_INT_CLEAR_ACR_CTS_MASK = BIT(0),
	HDMI_PKT_0_INT_CLEAR_ACR_CTS_OFFSET = 0,
	/* PKT_1_INT_STATUS field values */
	HDMI_PKT_1_INT_STATUS_NEW_ENTRY = BIT(6),
	HDMI_PKT_1_INT_STATUS_OVERFLOW = BIT(5),
	HDMI_PKT_1_INT_STATUS_UNDERFLOW = BIT(4),
	HDMI_PKT_1_INT_STATUS_THR_HIGH = BIT(2),
	HDMI_PKT_1_INT_STATUS_THR_PASS = BIT(1),
	HDMI_PKT_1_INT_STATUS_THR_LOW = BIT(0),
	/* PKT_1_INT_MASK_N field values */
	HDMI_PKT_1_INT_MASK_N_NEW_ENTRY_MASK = BIT(6),
	HDMI_PKT_1_INT_MASK_N_NEW_ENTRY_OFFSET = 6,
	HDMI_PKT_1_INT_MASK_N_OVERFLOW_MASK = BIT(5),
	HDMI_PKT_1_INT_MASK_N_OVERFLOW_OFFSET = 5,
	HDMI_PKT_1_INT_MASK_N_UNDERFLOW_MASK = BIT(4),
	HDMI_PKT_1_INT_MASK_N_UNDERFLOW_OFFSET = 4,
	HDMI_PKT_1_INT_MASK_N_THR_HIGH_MASK = BIT(2),
	HDMI_PKT_1_INT_MASK_N_THR_HIGH_OFFSET = 2,
	HDMI_PKT_1_INT_MASK_N_THR_PASS_MASK = BIT(1),
	HDMI_PKT_1_INT_MASK_N_THR_PASS_OFFSET = 1,
	HDMI_PKT_1_INT_MASK_N_THR_LOW_MASK = BIT(0),
	HDMI_PKT_1_INT_MASK_N_THR_LOW_OFFSET = 0,
	/* PKT_1_INT_CLEAR field values */
	HDMI_PKT_1_INT_CLEAR_NEW_ENTRY_MASK = BIT(6),
	HDMI_PKT_1_INT_CLEAR_NEW_ENTRY_OFFSET = 6,
	HDMI_PKT_1_INT_CLEAR_OVERFLOW_MASK = BIT(5),
	HDMI_PKT_1_INT_CLEAR_OVERFLOW_OFFSET = 5,
	HDMI_PKT_1_INT_CLEAR_UNDERFLOW_MASK = BIT(4),
	HDMI_PKT_1_INT_CLEAR_UNDERFLOW_OFFSET = 4,
	HDMI_PKT_1_INT_CLEAR_THR_HIGH_MASK = BIT(2),
	HDMI_PKT_1_INT_CLEAR_THR_HIGH_OFFSET = 2,
	HDMI_PKT_1_INT_CLEAR_THR_PASS_MASK = BIT(1),
	HDMI_PKT_1_INT_CLEAR_THR_PASS_OFFSET = 1,
	HDMI_PKT_1_INT_CLEAR_THR_LOW_MASK = BIT(0),
	HDMI_PKT_1_INT_CLEAR_THR_LOW_OFFSET = 0,
/* --- id_scdc_interrupt --- */
	/* SCDC_INT_STATUS field values */
	HDMI_SCDC_INT_STATUS_TMDS_CFG = BIT(2),
	HDMI_SCDC_INT_STATUS_SC = BIT(1),
	HDMI_SCDC_INT_STATUS_CFG = BIT(0),
	/* SCDC_INT_MASK_N field values */
	HDMI_SCDC_INT_MASK_N_TMDS_CFG_MASK = BIT(2),
	HDMI_SCDC_INT_MASK_N_TMDS_CFG_OFFSET = 2,
	HDMI_SCDC_INT_MASK_N_SC_MASK = BIT(1),
	HDMI_SCDC_INT_MASK_N_SC_OFFSET = 1,
	HDMI_SCDC_INT_MASK_N_CFG_MASK = BIT(0),
	HDMI_SCDC_INT_MASK_N_CFG_OFFSET = 0,
	/* SCDC_INT_CLEAR field values */
	HDMI_SCDC_INT_CLEAR_TMDS_CFG_MASK = BIT(2),
	HDMI_SCDC_INT_CLEAR_TMDS_CFG_OFFSET = 2,
	HDMI_SCDC_INT_CLEAR_SC_MASK = BIT(1),
	HDMI_SCDC_INT_CLEAR_SC_OFFSET = 1,
	HDMI_SCDC_INT_CLEAR_CFG_MASK = BIT(0),
	HDMI_SCDC_INT_CLEAR_CFG_OFFSET = 0,
/* --- id_hdcp_interrupt --- */
	/* HDCP_INT_STATUS field values */
	HDMI_HDCP_INT_STATUS_ENCDIS = BIT(8),
	HDMI_HDCP_INT_STATUS_ENCEN = BIT(7),
	/* HDCP_INT_MASK_N field values */
	HDMI_HDCP_INT_MASK_N_ENCDIS_MASK = BIT(8),
	HDMI_HDCP_INT_MASK_N_ENCDIS_OFFSET = 8,
	HDMI_HDCP_INT_MASK_N_ENCEN_MASK = BIT(7),
	HDMI_HDCP_INT_MASK_N_ENCEN_OFFSET = 7,
	/* HDCP_INT_CLEAR field values */
	HDMI_HDCP_INT_CLEAR_ENCDIS_MASK = BIT(8),
	HDMI_HDCP_INT_CLEAR_ENCDIS_OFFSET = 8,
	HDMI_HDCP_INT_CLEAR_ENCEN_MASK = BIT(7),
	HDMI_HDCP_INT_CLEAR_ENCEN_OFFSET = 7,
/* --- id_cec_interrupt --- */
	/* HDMI_CEC_INT_STATUS field values */
	HDMI_CEC_INT_STATUS_RX_NOTIFY_ERR = BIT(12),
	HDMI_CEC_INT_STATUS_RX_EOM = BIT(11),
	HDMI_CEC_INT_STATUS_TX_DRIVE_ERR = BIT(10),
	HDMI_CEC_INT_STATUS_RX_BUSY = BIT(9),
	HDMI_CEC_INT_STATUS_TX_BUSY = BIT(8),
	HDMI_CEC_INT_STATUS_TX_FRAME_DISCARDED = BIT(5),
	HDMI_CEC_INT_STATUS_TX_NRETRANSMIT_FAIL = BIT(4),
	HDMI_CEC_INT_STATUS_TX_LINE_ERR = BIT(3),
	HDMI_CEC_INT_STATUS_TX_ARBLOST = BIT(2),
	HDMI_CEC_INT_STATUS_TX_NACK = BIT(1),
	HDMI_CEC_INT_STATUS_TX_DONE = BIT(0),
	/* HDMI_CEC_INT_MASK_N field values */
	HDMI_CEC_INT_MASK_N_RX_NOTIFY_ERR_MASK = BIT(12),
	HDMI_CEC_INT_MASK_N_RX_NOTIFY_ERR_OFFSET = 12,
	HDMI_CEC_INT_MASK_N_RX_EOM_MASK = BIT(11),
	HDMI_CEC_INT_MASK_N_RX_EOM_OFFSET = 11,
	HDMI_CEC_INT_MASK_N_TX_DRIVE_ERR_MASK = BIT(10),
	HDMI_CEC_INT_MASK_N_TX_DRIVE_ERR_OFFSET = 10,
	HDMI_CEC_INT_MASK_N_RX_BUSY_MASK = BIT(9),
	HDMI_CEC_INT_MASK_N_RX_BUSY_OFFSET = 9,
	HDMI_CEC_INT_MASK_N_TX_BUSY_MASK = BIT(8),
	HDMI_CEC_INT_MASK_N_TX_BUSY_OFFSET = 8,
	HDMI_CEC_INT_MASK_N_TX_FRAME_DISCARDED_MASK = BIT(5),
	HDMI_CEC_INT_MASK_N_TX_FRAME_DISCARDED_OFFSET = 5,
	HDMI_CEC_INT_MASK_N_TX_NRETRANSMIT_FAIL_MASK = BIT(4),
	HDMI_CEC_INT_MASK_N_TX_NRETRANSMIT_FAIL_OFFSET = 4,
	HDMI_CEC_INT_MASK_N_TX_LINE_ERR_MASK = BIT(3),
	HDMI_CEC_INT_MASK_N_TX_LINE_ERR_OFFSET = 3,
	HDMI_CEC_INT_MASK_N_TX_ARBLOST_MASK = BIT(2),
	HDMI_CEC_INT_MASK_N_TX_ARBLOST_OFFSET = 2,
	HDMI_CEC_INT_MASK_N_TX_NACK_MASK = BIT(1),
	HDMI_CEC_INT_MASK_N_TX_NACK_OFFSET = 1,
	HDMI_CEC_INT_MASK_N_TX_DONE_MASK = BIT(0),
	HDMI_CEC_INT_MASK_N_TX_DONE_OFFSET = 0,
	/* HDMI_CEC_INT_CLEAR field values */
	HDMI_CEC_INT_CLEAR_RX_NOTIFY_ERR_MASK = BIT(12),
	HDMI_CEC_INT_CLEAR_RX_NOTIFY_ERR_OFFSET = 12,
	HDMI_CEC_INT_CLEAR_RX_EOM_MASK = BIT(11),
	HDMI_CEC_INT_CLEAR_RX_EOM_OFFSET = 11,
	HDMI_CEC_INT_CLEAR_TX_DRIVE_ERR_MASK = BIT(10),
	HDMI_CEC_INT_CLEAR_TX_DRIVE_ERR_OFFSET = 10,
	HDMI_CEC_INT_CLEAR_RX_BUSY_MASK = BIT(9),
	HDMI_CEC_INT_CLEAR_RX_BUSY_OFFSET = 9,
	HDMI_CEC_INT_CLEAR_TX_BUSY_MASK = BIT(8),
	HDMI_CEC_INT_CLEAR_TX_BUSY_OFFSET = 8,
	HDMI_CEC_INT_CLEAR_TX_FRAME_DISCARDED_MASK = BIT(5),
	HDMI_CEC_INT_CLEAR_TX_FRAME_DISCARDED_OFFSET = 5,
	HDMI_CEC_INT_CLEAR_TX_NRETRANSMIT_FAIL_MASK = BIT(4),
	HDMI_CEC_INT_CLEAR_TX_NRETRANSMIT_FAIL_OFFSET = 4,
	HDMI_CEC_INT_CLEAR_TX_LINE_ERR_MASK = BIT(3),
	HDMI_CEC_INT_CLEAR_TX_LINE_ERR_OFFSET = 3,
	HDMI_CEC_INT_CLEAR_TX_ARBLOST_MASK = BIT(2),
	HDMI_CEC_INT_CLEAR_TX_ARBLOST_OFFSET = 2,
	HDMI_CEC_INT_CLEAR_TX_NACK_MASK = BIT(1),
	HDMI_CEC_INT_CLEAR_TX_NACK_OFFSET = 1,
	HDMI_CEC_INT_CLEAR_TX_DONE_MASK = BIT(0),
	HDMI_CEC_INT_CLEAR_TX_DONE_OFFSET = 0,
};

/* Interrupts flags */
#define HDMI_IRQ_IF_FLAG				(\
				HDMI_PKT_0_INT_STATUS_AVIIF | \
				HDMI_PKT_0_INT_STATUS_SRCPDIF | \
				HDMI_PKT_0_INT_STATUS_AUDIF | \
				HDMI_PKT_0_INT_STATUS_VSIF | \
				HDMI_PKT_0_INT_STATUS_DRMIF)
#define HDMI_IRQ_AUDIO_AVP1_FLAG		(\
				HDMI_AVPUNIT_1_INT_STATUS_AUD_CHSTATUS_SP3 | \
				HDMI_AVPUNIT_1_INT_STATUS_AUD_CHSTATUS_SP2 | \
				HDMI_AVPUNIT_1_INT_STATUS_AUD_CHSTATUS_SP1 | \
				HDMI_AVPUNIT_1_INT_STATUS_AUD_CHSTATUS_SP0 | \
				HDMI_AVPUNIT_1_INT_STATUS_AFIFO_UNDERFLOW | \
				HDMI_AVPUNIT_1_INT_STATUS_AFIFO_OVERFLOW | \
				HDMI_AVPUNIT_1_INT_STATUS_AFIFO_THR_PASS | \
				HDMI_AVPUNIT_1_INT_STATUS_AUD_MUTE)
#define HDMI_IRQ_AUDIO_PKT0_FLAG		(\
				HDMI_PKT_0_INT_STATUS_ACR_N | \
				HDMI_PKT_0_INT_STATUS_ACR_CTS)
				//HDMI_PKT_0_INT_STATUS_GCP)
#define HDMI_IRQ_VIDEO_CHG_FLAG			(\
				HDMI_AVPUNIT_1_INT_STATUS_VMON_VMEAS | \
				HDMI_AVPUNIT_1_INT_STATUS_VMON_HMEAS)

#define HDMIRX_INTR_SYNC						0x01
#define HDMIRX_INTR_HDCP						0x02
#define HDMIRX_INTR_EDID						0x03
#define HDMIRX_INTR_PKT							0x04
#define HDMIRX_INTR_AVMUTE						0x05
#define HDMIRX_INTR_TMDS						0x06
#define HDMIRX_INTR_CHNL_STS					0x07
#define HDMIRX_INTR_CLR_DEPTH					0x08
#define HDMIRX_INTR_VSI_STOP					0x09
#define HDMIRX_INTR_GMD_PKT						0x0A
#define HDMIRX_INTR_HDCP_2X						0x0B
#define HDMIRX_INTR_PRT							0x0C

#endif
