# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_PHY_BERLIN_PCIE)		+= phy-berlin-pcie.o
obj-$(CONFIG_PHY_BERLIN_SATA)		+= phy-berlin-sata.o
obj-$(CONFIG_PHY_BERLIN_USB)		+= phy-berlin-usb.o
obj-$(CONFIG_PHY_SYNA_USB)		+= phy-syna-usb.o
