# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_RENESAS_MMNGRBUF)		+= mmngrbuf/
obj-$(CONFIG_RENESAS_MMNGR)		+= mmngr/
obj-$(CONFIG_RENESAS_UVCS_DRV)		+= uvcs_drv/
obj-$(CONFIG_RENESAS_VSPM_IF)		+= vspmif/
obj-$(CONFIG_RENESAS_VSPM)		+= vspm/
