spacemit-dummycodec-objs := spacemit-dummy-codec.o
spacemit-hdmiaudio-objs := spacemit-snd-sspa.o
spacemit-i2s-objs := spacemit-snd-i2s.o
spacemit-pcm-objs := spacemit-snd-pcm-dma.o
spacemit-card-objs := spacemit-snd-card.o

obj-$(CONFIG_SPACEMIT_DUMMYCODEC) += spacemit-dummycodec.o

obj-$(CONFIG_SPACEMIT_HDMIAUDIO) += spacemit-hdmiaudio.o

obj-$(CONFIG_SPACEMIT_I2S) += spacemit-i2s.o

obj-$(CONFIG_SPACEMIT_PCM) += spacemit-pcm.o

obj-$(CONFIG_SPACEMIT_CARD) += spacemit-card.o


