// SPDX-License-Identifier: GPL-2.0
/* Copyright (C) 2019-2020 Synaptics Incorporated */

#include "avio_dhub_cfg.h"
#include "avio_dhub_cfg_prv.h"

#define AVIO_DHUB_MV_R0_SIZE       (8704)
#define AVIO_DHUB_VMM_VX_R_SIZE    (512)
#define AVIO_DHUB_MV_R1_SIZE       (5632)
#define AVIO_DHUB_GFX_R1_SIZE      (16640)
#define AVIO_DHUB_1DSCL_W0_SIZE    (9152)
#define AVIO_DHUB_1DSCL_W1_SIZE    (2400)
#define AVIO_DHUB_MetaData_RD_SIZE (512)
#define AVIO_DHUB_DBEDR_RD_SIZE    (9152)
#define AVIO_DHUB_DBEDR_RD_C_SIZE  (2400)

#define AVIO_DHUB_MV_R0_BASE       (VPP_DHUB_BANK0_START_ADDR)
#define AVIO_DHUB_VMM_VX_R_BASE    (AVIO_DHUB_MV_R0_BASE + AVIO_DHUB_MV_R0_SIZE)
#define AVIO_DHUB_MV_R1_BASE	   (AVIO_DHUB_VMM_VX_R_BASE + AVIO_DHUB_VMM_VX_R_SIZE)
#define AVIO_DHUB_GFX_R1_BASE	   (AVIO_DHUB_MV_R1_BASE + AVIO_DHUB_MV_R1_SIZE)
#define AVIO_DHUB_1DSCL_W0_BASE	   (AVIO_DHUB_GFX_R1_BASE + AVIO_DHUB_GFX_R1_SIZE)
#define AVIO_DHUB_1DSCL_W1_BASE	   (AVIO_DHUB_1DSCL_W0_BASE + AVIO_DHUB_1DSCL_W0_SIZE)
#define AVIO_DHUB_MetaData_RD_BASE (AVIO_DHUB_1DSCL_W1_BASE + AVIO_DHUB_1DSCL_W1_SIZE)
#define AVIO_DHUB_DBEDR_RD_BASE	   (AVIO_DHUB_MetaData_RD_BASE + AVIO_DHUB_MetaData_RD_SIZE)

DHUB_channel_config  VPP_config[VPP_NUM_OF_CHANNELS] = {
	{ avioDhubChMap_vpp128b_MV_R0, AVIO_DHUB_MV_R0_BASE, AVIO_DHUB_MV_R0_BASE+64, 64, (AVIO_DHUB_MV_R0_SIZE-64), dHubChannel_CFG_MTU_256byte, 1, 0, 1, 0xF, 0xF},
	{ avioDhubChMap_vpp128b_VMM_VX_R, AVIO_DHUB_VMM_VX_R_BASE, AVIO_DHUB_VMM_VX_R_BASE+64, 64, (AVIO_DHUB_VMM_VX_R_SIZE-64), dHubChannel_CFG_MTU_256byte, 1, 0, 1, 0xF, 0xF},
	{ avioDhubChMap_vpp128b_MV_R1, AVIO_DHUB_MV_R1_BASE, AVIO_DHUB_MV_R1_BASE+64, 64, (AVIO_DHUB_MV_R1_SIZE-64), dHubChannel_CFG_MTU_256byte, 1, 0, 1, 0xF, 0xF},
	{ avioDhubChMap_vpp128b_GFX_R1, AVIO_DHUB_GFX_R1_BASE, AVIO_DHUB_GFX_R1_BASE+64, 64, (AVIO_DHUB_GFX_R1_SIZE-64), dHubChannel_CFG_MTU_256byte, 1, 0, 1, 0xF, 0xF},
	{ avioDhubChMap_vpp128b_1DSCL_W0, AVIO_DHUB_1DSCL_W0_BASE, AVIO_DHUB_1DSCL_W0_BASE+64, 64, (AVIO_DHUB_1DSCL_W0_SIZE-64), dHubChannel_CFG_MTU_256byte, 1, 0, 1, 0xF, 0xF},
	{ avioDhubChMap_vpp128b_1DSCL_W1, AVIO_DHUB_1DSCL_W1_BASE, AVIO_DHUB_1DSCL_W1_BASE+64, 64, (AVIO_DHUB_1DSCL_W1_SIZE-64), dHubChannel_CFG_MTU_256byte, 1, 0, 1, 0xF, 0xF},
	{ avioDhubChMap_vpp128b_MetaData_RD, AVIO_DHUB_MetaData_RD_BASE, AVIO_DHUB_MetaData_RD_BASE+64, 64, (AVIO_DHUB_MetaData_RD_SIZE-64), dHubChannel_CFG_MTU_256byte, 1, 0, 1, 0xF, 0xF},
	{ avioDhubChMap_vpp128b_DBEDR_RD, AVIO_DHUB_DBEDR_RD_BASE, AVIO_DHUB_DBEDR_RD_BASE+64, 64, (AVIO_DHUB_DBEDR_RD_SIZE-64), dHubChannel_CFG_MTU_256byte, 1, 0, 1, 0xF, 0xF},
};

#define AIO_DHUB_PRI_SIZE		    (2048)
#define AIO_DHUB_GFX2_R1_SIZE	    (0)
#define AIO_DHUB_SEC_SIZE		    (512)
#define AIO_DHUB_SPDIF1_SIZE		(0)
#define AIO_DHUB_PDM_SIZE		    (2048)
#define AIO_DHUB_MIC1_SIZE		    (2048)
#define AIO_DHUB_MIC2_SIZE		    (512)
#define AIO_DHUB_HDMI_SIZE		    (2048)
#define AIO_DHUB_BCM_SIZE		    (512)
#define AIO_DHUB_MIC3_SIZE		    (0)
#define AIO_DHUB_MIC4_SIZE		    (2048)
#define AIO_DHUB_MIC5_SIZE		    (2048)
#define AIO_DHUB_DMIC_R_SIZE		(1024)
#define AIO_DHUB_DMIC_W_SIZE		(0)
#define AIO_DHUB_SPDIFTX_SIZE	    (2048)
#define AIO_DHUB_SPDIFRX_SIZE	    (2048)

#define AIO_DHUB_PRI_BASE		    (AG_DHUB_BANK0_START_ADDR)
#define AIO_DHUB_GFX2_R1_BASE	    (AIO_DHUB_PRI_BASE+AIO_DHUB_PRI_SIZE)
#define AIO_DHUB_SEC_BASE		    (AIO_DHUB_GFX2_R1_BASE+AIO_DHUB_GFX2_R1_SIZE)
#define AIO_DHUB_SPDIF1_BASE		(AIO_DHUB_SEC_BASE+AIO_DHUB_SEC_SIZE)
#define AIO_DHUB_PDM_BASE		    (AIO_DHUB_SPDIF1_BASE+AIO_DHUB_SPDIF1_SIZE)
#define AIO_DHUB_MIC1_BASE		    (AIO_DHUB_PDM_BASE+AIO_DHUB_PDM_SIZE)
#define AIO_DHUB_MIC2_BASE		    (AIO_DHUB_MIC1_BASE+AIO_DHUB_MIC1_SIZE)
#define AIO_DHUB_HDMI_BASE		    (AIO_DHUB_MIC2_BASE+AIO_DHUB_MIC2_SIZE)
#define AIO_DHUB_BCM_BASE		    (AIO_DHUB_HDMI_BASE+AIO_DHUB_HDMI_SIZE)
#define AIO_DHUB_MIC3_BASE		    (AIO_DHUB_BCM_BASE+AIO_DHUB_BCM_SIZE)
#define AIO_DHUB_MIC4_BASE		    (AIO_DHUB_MIC3_BASE+AIO_DHUB_MIC3_SIZE)
#define AIO_DHUB_MIC5_BASE		    (AIO_DHUB_MIC4_BASE+AIO_DHUB_MIC4_SIZE)
#define AIO_DHUB_DMIC_R_BASE		(AIO_DHUB_MIC5_BASE+AIO_DHUB_MIC5_SIZE)
#define AIO_DHUB_DMIC_W_BASE		(AIO_DHUB_DMIC_R_BASE+AIO_DHUB_DMIC_R_SIZE)
#define AIO_DHUB_SPDIFTX_BASE	    (AIO_DHUB_DMIC_W_BASE+AIO_DHUB_DMIC_W_SIZE)
#define AIO_DHUB_SPDIFRX_BASE	    (AIO_DHUB_SPDIFTX_BASE+AIO_DHUB_SPDIFTX_SIZE)

DHUB_channel_config  AG_config[AG_NUM_OF_CHANNELS] = {
	 // Bank0
	{ avioDhubChMap_aio64b_MA0_R, AIO_DHUB_PRI_BASE, AIO_DHUB_PRI_BASE+32, 32, (AIO_DHUB_PRI_SIZE-32), dHubChannel_CFG_MTU_128byte, 0, 0, 1, 0xF, 0xF},
	{ avioDhubChMap_aio64b_GFX2_R, AIO_DHUB_GFX2_R1_BASE, AIO_DHUB_GFX2_R1_BASE+64, 64, (AIO_DHUB_GFX2_R1_SIZE-64), dHubChannel_CFG_MTU_128byte, 1, 0, 1, 0xF, 0xF},
	{ avioDhubChMap_aio64b_MA2_R, AIO_DHUB_SEC_BASE, AIO_DHUB_SEC_BASE+32, 32, (AIO_DHUB_SEC_SIZE-32), dHubChannel_CFG_MTU_128byte, 0, 0, 1, 0xF, 0xF},
	{ avioDhubChMap_aio64b_MA3_R, AIO_DHUB_SPDIF1_BASE, AIO_DHUB_SPDIF1_BASE+32, 32, (AIO_DHUB_SPDIF1_SIZE-32), dHubChannel_CFG_MTU_128byte, 0, 0, 1, 0xF, 0xF},
	{ avioDhubChMap_aio64b_PDM_CH_W, AIO_DHUB_PDM_BASE, AIO_DHUB_PDM_BASE+32, 32, (AIO_DHUB_PDM_SIZE-32), dHubChannel_CFG_MTU_128byte, 0, 0, 1, 0xF, 0xF},
	{ avioDhubChMap_aio64b_MIC1_CH_W, AIO_DHUB_MIC1_BASE, AIO_DHUB_MIC1_BASE+32, 32, (AIO_DHUB_MIC1_SIZE-32), dHubChannel_CFG_MTU_128byte, 0, 0, 1, 0xF, 0xF},
	{ avioDhubChMap_aio64b_MIC2_CH_W, AIO_DHUB_MIC2_BASE, AIO_DHUB_MIC2_BASE+32, 32, (AIO_DHUB_MIC2_SIZE-32), dHubChannel_CFG_MTU_128byte, 0, 0, 1, 0xF, 0xF},
	{ avioDhubChMap_aio64b_HDMI_R, AIO_DHUB_HDMI_BASE, AIO_DHUB_HDMI_BASE+32, 32, (AIO_DHUB_HDMI_SIZE-32), dHubChannel_CFG_MTU_128byte, 0, 0, 1, 0xF, 0xF},
	{ avioDhubChMap_aio64b_BCM_R, AIO_DHUB_BCM_BASE, AIO_DHUB_BCM_BASE+128, 128, (AIO_DHUB_BCM_SIZE-128), dHubChannel_CFG_MTU_128byte, 0, 0, 1, 0xF, 0xF},
	{ avioDhubChMap_aio64b_MIC3_CH_W, AIO_DHUB_MIC3_BASE, AIO_DHUB_MIC3_BASE+32, 32, (AIO_DHUB_MIC3_SIZE-32), dHubChannel_CFG_MTU_128byte, 0, 0, 1, 0xF, 0xF},
	{ avioDhubChMap_aio64b_MIC4_CH_W, AIO_DHUB_MIC4_BASE, AIO_DHUB_MIC4_BASE+32, 32, (AIO_DHUB_MIC4_SIZE-32), dHubChannel_CFG_MTU_128byte, 0, 0, 1, 0xF, 0xF},
	{ avioDhubChMap_aio64b_MIC5_CH_W, AIO_DHUB_MIC5_BASE, AIO_DHUB_MIC5_BASE+32, 32, (AIO_DHUB_MIC5_SIZE-32), dHubChannel_CFG_MTU_128byte, 0, 0, 1, 0xF, 0xF},
	{ avioDhubChMap_aio64b_PDM_CH_R, AIO_DHUB_DMIC_R_BASE, AIO_DHUB_DMIC_R_BASE+32, 32, (AIO_DHUB_DMIC_R_SIZE-32), dHubChannel_CFG_MTU_128byte, 0, 0, 1, 0xF, 0xF},
	{ avioDhubChMap_aio64b_DMIC_PDM_CH_W, AIO_DHUB_DMIC_W_BASE, AIO_DHUB_DMIC_W_BASE+32, 32, (AIO_DHUB_DMIC_W_SIZE-32), dHubChannel_CFG_MTU_128byte, 0, 0, 1, 0xF, 0xF},
	{ avioDhubChMap_aio64b_SPDIF_R, AIO_DHUB_SPDIFTX_BASE, AIO_DHUB_SPDIFTX_BASE+32, 32, (AIO_DHUB_SPDIFTX_SIZE-32), dHubChannel_CFG_MTU_128byte, 0, 0, 1, 0xF, 0xF},
	{ avioDhubChMap_aio64b_SPDIF_W, AIO_DHUB_SPDIFRX_BASE, AIO_DHUB_SPDIFRX_BASE+32, 32, (AIO_DHUB_SPDIFRX_SIZE-32), dHubChannel_CFG_MTU_128byte, 0, 0, 1, 0xF, 0xF},
};
