# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_ION) += ion_page_pool.o

obj-$(CONFIG_ION_SYSTEM_HEAP) += ion_sys_heap.o
ion_sys_heap-y := ion_system_heap.o

obj-$(CONFIG_ION_HEAP_EXTRA) += ion_heap_extra.o
obj-$(CONFIG_ION_CMA_HEAP) += ion_cma_heap.o
obj-$(CONFIG_ION_BERLIN_HEAP) += ion_berlin_heap.o
obj-$(CONFIG_ION_SYSTEM_CUST_HEAP) += ion_system_cust_heap.o
obj-$(CONFIG_ION_CMA_CUST_HEAP) += ion_cma_cust_heap.o
