# SPDX-License-Identifier: GPL-2.0
# Berlin SoC Family
dtb-$(CONFIG_ARCH_BERLIN) += berlin4ct-dmp.dtb
dtb-$(CONFIG_ARCH_BERLIN) += berlin4ct-stb.dtb
dtb-$(CONFIG_ARCH_BERLIN) += vs680-a0-evk.dtb
dtb-$(CONFIG_ARCH_BERLIN) += vs680-a0-c02.dtb
dtb-$(CONFIG_ARCH_BERLIN) += vs680-a0-c05.dtb
dtb-$(CONFIG_ARCH_BERLIN) += vs680-a0-bpi-m6.dtb
dtb-$(CONFIG_ARCH_BERLIN) += vs680-a0-bpi-m6-0806.dtb
