# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the Renesas capture/playback device drivers.
#

obj-$(CONFIG_VIDEO_RCAR_VIN) += rcar-vin/
obj-$(CONFIG_VIDEO_RZG2L_CRU) += rzg2l-cru/
obj-$(CONFIG_VIDEO_RZG2L_CRU_YUV) += rzg2l-cru-yuv/
obj-$(CONFIG_VIDEO_RENESAS_VSP1) += vsp1/

obj-$(CONFIG_VIDEO_RZV2N_IVC)      += rzv2n-ivc/

obj-$(CONFIG_VIDEO_RCAR_DRIF) += rcar_drif.o
obj-$(CONFIG_VIDEO_RCAR_ISP) += rcar-isp.o
obj-$(CONFIG_VIDEO_RENESAS_CEU) += renesas-ceu.o
obj-$(CONFIG_VIDEO_RENESAS_FCP) += rcar-fcp.o
obj-$(CONFIG_VIDEO_RENESAS_FDP1) += rcar_fdp1.o
obj-$(CONFIG_VIDEO_RENESAS_JPU) += rcar_jpu.o
obj-$(CONFIG_VIDEO_SH_VOU) += sh_vou.o
