# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux Ethercat native device driver.
#

obj-$(CONFIG_EC_GENERIC) += ec_generic.o
obj-$(CONFIG_EC_K1X_EMAC) += ec_k1x.o
ec_k1x-y += ec_k1x_emac.o
