# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 Synaptics Incorporated

#
# VIP kernel module: synap.ko
#

MODULE_NAME ?= synap

EXTRA_CFLAGS += -Werror

EXTRA_CFLAGS += -DDEVICE_NAME=\"synap\"

EXTRA_CFLAGS += -I$(srctree)/drivers/synap/kernel/src \
                -I$(srctree)/drivers/synap/kernel/inc

# Access to TA commands
EXTRA_CFLAGS += -I$(srctree)/drivers/synap/ta/inc

TEE_INC_PATH += -I$(srctree)/drivers/soc/berlin/modules/tzd/tee/client_api \
                -I$(srctree)/drivers/soc/berlin/modules/tzd/tee/common \
                -I$(srctree)/drivers/soc/berlin/modules/tzd/tz/common \
                -I$(srctree)/drivers/soc/berlin/modules/tzd/include \
                -I$(srctree)/drivers/soc/berlin/modules/tzd

ION_INC_PATH += -I$(srctree)/drivers/staging/android/ion
EBG_INC_PATH += -I$(srctree)/drivers/synap/common/inc

EXTRA_CFLAGS += $(TEE_INC_PATH) $(ION_INC_PATH) $(EBG_INC_PATH)

OBJS := src/synap_kernel.o \
        src/synap_kernel_drv.o \
        src/synap_kernel_ca.o \
        src/synap_kernel_stats.o \
        src/synap_mem.o \
        src/synap_profile.o \
        ../common/src/ebg_file.o

ifeq ($(DEBUG), 1)
    EXTRA_CFLAGS += -DDEBUG_LEVEL=2
endif


obj-$(CONFIG_SYNAP) += $(MODULE_NAME).o

$(MODULE_NAME)-objs  = $(OBJS)
