
obj-$(CONFIG_TOUCHSCREEN_GT9XX) += gt9xx_ts.o
#obj-y += gt9xx_ts.o
gt9xx_ts-objs := gt9xx.o
gt9xx_ts-objs += gt9xx_update.o
gt9xx_ts-objs += goodix_tool.o

#all:
#    @$(MAKE) --no-print-directory -C $(KERNEL_SRC) SUBDIRS=$(CURDIR) M=${PWD} modules

#modules_install:
#    @$(MAKE) --no-print-directory -C $(KERNEL_SRC) \
#               SUBDIRS=$(CURDIR) modules_install
