# SPDX-License-Identifier: GPL-2.0

dtbo-$(CONFIG_BOARD_BANANAPI_M4ZERO) += \
	bpi-m4zero-i2c0.dtbo \
	bpi-m4zero-i2c1.dtbo \
	bpi-m4zero-uart4.dtbo \
	bpi-m4zero-uart5.dtbo \
	bpi-m4zero-pwm2.dtbo \
	bpi-m4zero-pwm2-beeper.dtbo \
	bpi-m4zero-pwm2-fan.dtbo \
	bpi-m4zero-spi1.dtbo \
	bpi-m4zero-spi1-flash.dtbo \
	bpi-m4zero-spdifout.dtbo \
	bpi-m4zero-i2smic-mems.dtbo \
	bpi-m4zero-nxez-pcm512x-hifi.dtbo \
	bpi-m4zero-waveshare-wm8960-hifi.dtbo \
	bpi-m4zero-ds3231.dtbo

targets += $(dtbo-y)
always	:= $(dtbo-y)
clean-files := *.dtbo
